### ISSUE TITLE
`path.Path().files()` fails with `FileNotFoundError`

### ISSUE THREAD

**Issue by 5j9** [jaraco/path#212]
```python
>>> import path, pathlib
>>> pathlib.Path()
WindowsPath('.')
>>> path.Path()
Path('')
>>> list(pathlib.Path().iterdir())
[WindowsPath('.git'),
 WindowsPath('.idea'),
 WindowsPath('LICENSE'),
 WindowsPath('pyproject.toml'),
 WindowsPath('README.rst'),
 WindowsPath('setup.cfg')]
>>> path.Path().files()
Traceback (most recent call last):
  File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\site-packages\IPython\core\interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-43-109000f98fc0>", line 1, in <module>
    path.Path().files()
  File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\site-packages\path\__init__.py", line 514, in files
    return [p for p in self.listdir(*args, **kwargs) if p.isfile()]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\site-packages\path\__init__.py", line 492, in listdir
    return list(filter(match, (self / child for child in os.listdir(self))))
                                                         ^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: Path('')
>>> path.Path('.').files()
[Path('.\\LICENSE'),
 Path('.\\pyproject.toml'),
 Path('.\\README.rst'),
 Path('.\\setup.cfg')]
```

I expect `path.Path().files()` to work just like `path.Path('.').files()`, but it currently raises error. Is that intentional or is it a bug?
This is not a Windows-specific issue. There is a similar error on my Linux machine: `FileNotFoundError: [Errno 2] No such file or directory: Path('')`.

**Comment by jaraco** [comment]
> Is that intentional or is it a bug?

It's probably neither intentional nor a bug but a yet unexplored use-case ;)

Note that pathlib explicitly replaces the empty constructor with the `'.'` path:

```
>>> pathlib.Path()
PosixPath('.')
```

This project does aspire to align with pathlib where possible, so it should probably do the same (and probably implement `iterdir` at the same time, if it's not present already).

**Comment by jaraco** [comment]
Would you be willing to work on a patch?
